apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ci
spec:
  additionalKernelArgs:
  - "nmi_watchdog=0"
  - "audit=0"
  - "mce=off"
  - "processor.max_cstate=1"
  - "idle=poll"
  - "intel_idle.max_cstate=0"    
  cpu:
    isolated: "1-3"
    reserved: "0"
  hugepages:
    pages:
    - size: "1G"
      count: 1
      node: 0
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""
