apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ci
spec:
  cpu:
    isolated: "1-3"
    nonIsolated: "0"
    reserved: "0-1"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 1
  realTimeKernel:
    repoURL: "http://download-node-02.eng.bos.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1.1/compose/RT/x86_64/os"
