apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ci
spec:
  cpu:
    isolated: "1-3"
    nonIsolated: "0"
    reserved: "0-1"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 1
      node: 0
    - size: "2M"
      count: 128
  realTimeKernel:
    enabled: true
