apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: performanceprofiles.performance.openshift.io
spec:
  group: performance.openshift.io
  names:
    kind: PerformanceProfile
    listKind: PerformanceProfileList
    plural: performanceprofiles
    singular: performanceprofile
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PerformanceProfile is the Schema for the performanceprofiles API.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PerformanceProfileSpec defines the desired state of PerformanceProfile.
          properties:
            cpu:
              description: CPU defines set of CPU related parameters.
              properties:
                isolated:
                  description: Isolated defines set of CPU's that will used to give
                    to application threads the most execution time possible, which
                    means removing as many extraneous tasks off a CPU as possible.
                  type: string
                nonIsolated:
                  description: NonIsolated defines set of CPU's that will be used
                    for OS tasks, like serving interupts or workqueues.
                  type: string
                reserved:
                  description: Reserved defines set of CPU's that will not be used
                    for any container workloads initiated by kubelet.
                  type: string
              type: object
            hugepages:
              description: HugePages defines set of huge pages related parameters.
              properties:
                defaultHugepagesSize:
                  description: DefaultHugePagesSize defines huge pages default size
                    under kernel boot parameters.
                  type: string
                pages:
                  description: Pages defines huge pages that we want to allocate on
                    the boot time.
                  items:
                    description: HugePage defines the number of allocated huge pages
                      of the specific size.
                    properties:
                      count:
                        description: Count defines amount of huge pages, maps to the
                          'hugepages' kernel boot parameter.
                        format: int32
                        type: integer
                      size:
                        description: Size defines huge page size, maps to the 'hugepagesz'
                          kernel boot parameter.
                        type: string
                    type: object
                  type: array
              type: object
            nodeSelector:
              additionalProperties:
                type: string
              description: NodeSelector is a selector which must be true for the performance
                profile to fit on a node.
              type: object
            realTimeKernel:
              description: RealTimeKernel defines set of real time kernel related
                parameters.
              properties:
                enabled:
                  description: Enabled defines if the real time kernel packages should
                    be installed
                  type: boolean
              type: object
          type: object
        status:
          description: PerformanceProfileStatus defines the observed state of PerformanceProfile.
          properties:
            conditions:
              description: conditions represents the latest available observations
                of current state.
              items:
                description: PerformanceProfileCondition contains condition information
                  for an PerformanceProfile.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the timestamp corresponding
                      to the last status change of this condition.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human readable description of the details
                      of the last transition, complementing reason.
                    type: string
                  reason:
                    description: Reason is a brief machine readable explanation for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of ('True', 'False',
                      'Unknown').
                    type: string
                  type:
                    description: Type of the condition, currently ('Done', 'Updating',
                      'Failed').
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            machineCount:
              description: MachineCount represents the total number of machines targeted
                by the performance profile.
              format: int32
              type: integer
            unavailableMachineCount:
              description: UnavailableMachineCount represents the total number of
                unavailable (non-ready) machines targeted by performance profile.
                A node is marked unavailable if it is in updating state or NodeReady
                condition is false.
              format: int32
              type: integer
            updatedMachineCount:
              description: UpdatedMachineCount represents the total number of machines
                that updated with parameters from the performance profile and ready
                for action.
              format: int32
              type: integer
          required:
          - machineCount
          - unavailableMachineCount
          - updatedMachineCount
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
